# Generated by Django 3.2 on 2021-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batx_seminaris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='assignat',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SeminariAssignat',
        ),
    ]
