# Generated by Django 3.2 on 2021-05-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batx_seminaris', '0002_solicitud_assignat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'permissions': (('enviar_solicitud', 'Pot enviar Solicitud'),)},
        ),
    ]
