# Generated by Django 3.2 on 2021-05-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batx_seminaris', '0003_alter_solicitud_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'permissions': (('gestio_professor', 'Pot mantenir formulari i assignar projecte'),)},
        ),
    ]
