# Generated by Django 3.2.2 on 2021-05-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batxillerat_projecte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={},
        ),
    ]
