# Generated by Django 3.2.2 on 2021-05-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batxillerat_projecte', '0002_alter_departament_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={},
        ),
    ]
