# Generated by Django 3.2 on 2021-04-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('descripcio', models.CharField(max_length=200)),
                ('data_limit_inici', models.DateField()),
                ('data_limit_fi', models.DateField()),
            ],
        ),
    ]
