# Generated by Django 3.2.2 on 2021-05-15 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('descripcio', models.CharField(max_length=200)),
                ('data_limit_inici', models.DateField()),
                ('data_limit_fi', models.DateField()),
                ('url_acces', models.CharField(blank=True, max_length=60)),
                ('url_backend', models.CharField(blank=True, max_length=60)),
                ('llista_encarregats', models.ManyToManyField(limit_choices_to={'rol__id_rol': 1}, to=settings.AUTH_USER_MODEL)),
                ('llista_grups', models.ManyToManyField(to='auth.Group')),
            ],
            options={
                'verbose_name_plural': 'Aplicacions',
            },
            managers=[
                ('llistatAplicacions', django.db.models.manager.Manager()),
            ],
        ),
    ]
