# Generated by Django 3.2.2 on 2021-05-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacio',
            options={'verbose_name_plural': 'Aplicacions'},
        ),
    ]
