# Generated by Django 3.2.2 on 2021-05-19 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aplicacio',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='aplicacio',
            name='llista_encarregats',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol__id_rol': 1}, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aplicacio',
            name='llista_grups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
