# Generated by Django 3.2 on 2021-05-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('aplicacions', '0002_alter_aplicacio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacio',
            name='llista_grups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='aplicacio',
            name='url_acces',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='aplicacio',
            name='url_backend',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
