# Generated by Django 3.2 on 2021-05-14 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacions', '0003_auto_20210513_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacio',
            name='llista_encarregats',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
