# Generated by Django 3.2 on 2021-05-14 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicacions', '0005_alter_aplicacio_llista_encarregats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacio',
            name='llista_encarregats',
            field=models.ManyToManyField(limit_choices_to={'rol': 2}, to=settings.AUTH_USER_MODEL),
        ),
    ]
