# Generated by Django 3.2 on 2021-05-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
