# Generated by Django 3.2.2 on 2021-05-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curs',
            options={'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Grups'},
        ),
    ]
